vim.g.mapleader = " "

vim.keymap.set("n", "<leader>o", "<C-w>o", { desc = "Only keep current window" })
vim.keymap.set("n", "<leader>e", ":Ve<CR>", { desc = "Open netrw" })
vim.keymap.set("n", "<leader>w", ":w<CR>", { desc = "Save" })
vim.keymap.set("n", "<leader>q", ":q<CR>", { desc = "Quit" })
vim.keymap.set('n', '<C-k>', function() vim.cmd('resize +5') end, { desc = "Increase window height by 5" })
vim.keymap.set('n', '<C-j>', function() vim.cmd('resize -5') end, { desc = "Decrease window height by 5" })
vim.keymap.set('n', '<C-h>', function() vim.cmd('vertical resize -5') end, { desc = "Decrease window width by 5" })
vim.keymap.set('n', '<C-l>', function() vim.cmd('vertical resize +5') end, { desc = "Increase window width by 5" })
vim.keymap.set('n', '<C-=>', '<C-w>=', { noremap = true, desc = "Equalize all splits" })

vim.keymap.set('t', '<Esc>', [[<C-\><C-n>]], { noremap = true, silent = true })
vim.keymap.set('n', '<leader>t', function()
  vim.cmd('vsplit | terminal')
end, { desc = 'Open terminal in vertical split', noremap = true, silent = true })
vim.keymap.set('n', '<leader>T', function()
  vim.cmd('tabnew | terminal')
end, { desc = 'Open terminal in new tab', noremap = true, silent = true })

local fzf = require("fzf-lua")

vim.keymap.set("n", "<leader>ff", function()
  fzf.files()
end, { desc = "FzfLua Files" })
vim.keymap.set("n", "<leader>fg", function()
  fzf.live_grep()
end, { desc = "FzfLua Files" })
vim.keymap.set("n", "<leader>fb", function()
  fzf.buffers()
end, { desc = "FzfLua Buffers" })
vim.keymap.set("n", "<leader>fr", function()
  fzf.resume()
end,  { desc = "FzfLua Resume" })
